# -*- coding: utf-8 -*-
"""Keyboard vs Mouse Image Classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AlXtgRMW6Exa9lQMEnvCenNk8x6hb9U2

##Step1 - Install libraries
"""

!pip install tensorflow matplotlib seaborn scikit-learn pillow

"""##Step 2 - Import dataset"""

!git clone https://github.com/ramdhote05/CNN_Project.git

import os

print(os.listdir("CNN_Project"))

"""##Step 3 - Find dataset folder"""

import os

for root, dirs, files in os.walk("CNN_Project"):
    print(root)

#Setting path
keyboard_path = "CNN_Project/Keyboard_dataset"
mouse_path = "CNN_Project/Mouse_dataset"

#Check no. of images
keyboard_images = os.listdir(keyboard_path)
mouse_images = os.listdir(mouse_path)

print("Keyboard images:", len(keyboard_images))
print("Mouse images:", len(mouse_images))

"""##Step 4 - Exploring dataset"""

#Keyboard
import matplotlib.pyplot as plt
from PIL import Image
import os

plt.figure(figsize=(12, 8))

for i, filename in enumerate(keyboard_images[:6]):
    image_path = os.path.join(keyboard_path, filename)

    try:
        image = Image.open(image_path)

        plt.subplot(2, 3, i + 1)
        plt.imshow(image)
        plt.title("Keyboard")
        plt.axis("off")

    except:
        pass

plt.tight_layout()
plt.show()

#mouse
plt.figure(figsize=(12, 8))

for i, filename in enumerate(mouse_images[:6]):
    image_path = os.path.join(mouse_path, filename)

    try:
        image = Image.open(image_path)

        plt.subplot(2, 3, i + 1)
        plt.imshow(image)
        plt.title("Mouse")
        plt.axis("off")

    except:
        pass

plt.tight_layout()
plt.show()

"""##Step 5 - Check image dimensions"""

#Keyboard
from PIL import Image
import os

print("Keyboard image sizes:")

for filename in keyboard_images[:10]:
    try:
        image = Image.open(os.path.join(keyboard_path, filename))
        print(filename, image.size)
    except:
        pass

#mouse
print("Mouse image sizes:")

for filename in mouse_images[:10]:
    try:
        image = Image.open(os.path.join(mouse_path, filename))
        print(filename, image.size)
    except:
        pass

"""###Our all images have different resolutions thats why we will resize everything into 128 × 128 pixels

##Step 6 - Creating dataset
"""

#use TensorFlow's image_dataset_from_directory.
import os
import shutil

base_dir = "CNN_Project"

combined_dir = "CNN_Project/combined_dataset"

keyboard_combined = os.path.join(combined_dir, "Keyboard")
mouse_combined = os.path.join(combined_dir, "Mouse")

os.makedirs(keyboard_combined, exist_ok=True)
os.makedirs(mouse_combined, exist_ok=True)

#copy keyboard images
for filename in os.listdir(keyboard_path):

    source = os.path.join(keyboard_path, filename)
    destination = os.path.join(keyboard_combined, filename)

    if os.path.isfile(source):
        shutil.copy2(source, destination)

#copy mouse images
for filename in os.listdir(mouse_path):

    source = os.path.join(mouse_path, filename)
    destination = os.path.join(mouse_combined, filename)

    if os.path.isfile(source):
        shutil.copy2(source, destination)

print("Keyboard:", len(os.listdir(keyboard_combined)))
print("Mouse:", len(os.listdir(mouse_combined)))

"""##Step 7 - Load dataset  using tensorflow"""

import tensorflow as tf

print("TensorFlow version:", tf.__version__)

#Set parameters
IMG_SIZE = (128, 128)
BATCH_SIZE = 32
SEED = 42

#Load training dataset
train_ds = tf.keras.utils.image_dataset_from_directory(
    combined_dir,
    validation_split=0.30,
    subset="training",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

#Load test dataset
val_test_ds = tf.keras.utils.image_dataset_from_directory(
    combined_dir,
    validation_split=0.30,
    subset="validation",
    seed=SEED,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

class_names = train_ds.class_names

print(class_names)

"""##Step 8 - Create validation and tests dataset"""

# currently we have
# 70% Training
# 30% Validation + Test

# We will split that 30% into
# 15% Validation
# 15% Test

#Calculate the no. of batches
val_test_batches = tf.data.experimental.cardinality(val_test_ds)

print("Validation/Test batches:", val_test_batches)

#Split
test_batches = val_test_batches // 2

test_ds = val_test_ds.take(test_batches)
val_ds = val_test_ds.skip(test_batches)

#now
# Training → 70%
# Validation → 15%
# Testing → 15%

"""##Step 9 - Visual training images"""

plt.figure(figsize=(10, 10))

for images, labels in train_ds.take(1):

    for i in range(9):

        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(class_names[labels[i]])
        plt.axis("off")

plt.tight_layout()
plt.show()

"""##Step 10 - improve dataset performance"""

#using tensorflow prefetching
AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.prefetch(buffer_size=AUTOTUNE)
test_ds = test_ds.prefetch(buffer_size=AUTOTUNE)

"""##Step 11 - add data agumentation"""

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.1),
    tf.keras.layers.RandomZoom(0.1)
])

#Visualization
plt.figure(figsize=(10, 10))

for images, labels in train_ds.take(1):

    first_image = images[0]

    for i in range(9):

        augmented_image = data_augmentation(
            tf.expand_dims(first_image, 0)
        )

        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(
            augmented_image[0].numpy().astype("uint8")
        )
        plt.axis("off")

plt.tight_layout()
plt.show()

"""##Step 12 - Build the CNN"""

model = tf.keras.Sequential([

    # Data augmentation
    data_augmentation,

    # Normalize pixels
    tf.keras.layers.Rescaling(1./255),

    # CNN Layer 1
    tf.keras.layers.Conv2D(
        32,
        (3, 3),
        activation="relu"
    ),
    tf.keras.layers.MaxPooling2D(),

    # CNN Layer 2
    tf.keras.layers.Conv2D(
        64,
        (3, 3),
        activation="relu"
    ),
    tf.keras.layers.MaxPooling2D(),

    # CNN Layer 3
    tf.keras.layers.Conv2D(
        128,
        (3, 3),
        activation="relu"
    ),
    tf.keras.layers.MaxPooling2D(),

    # Convert feature maps to vector
    tf.keras.layers.Flatten(),

    # Fully connected layer
    tf.keras.layers.Dense(
        128,
        activation="relu"
    ),

    # Prevent overfitting
    tf.keras.layers.Dropout(0.5),

    # Binary classification
    tf.keras.layers.Dense(
        1,
        activation="sigmoid"
    )
])

"""##Step 13 - View model architecture"""

model.summary()

"""##Step 14 - model compilation"""

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

"""##Step 15 - Training CNN model"""

EPOCHS = 15

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS
)

"""##Step 16 - Plot training accuracy"""

plt.figure(figsize=(8, 5))

plt.plot(
    history.history["accuracy"],
    label="Training Accuracy"
)

plt.plot(
    history.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training vs Validation Accuracy")
plt.legend()
plt.grid()

plt.show()

"""##Step 17 - Plot training loss"""

plt.figure(figsize=(8, 5))

plt.plot(
    history.history["loss"],
    label="Training Loss"
)

plt.plot(
    history.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid()

plt.show()

#These two above graphs are important for explaining whether our model is underfitting or overfitting.

"""##Step 18 - Evaluate on test data"""

test_loss, test_accuracy = model.evaluate(val_test_ds)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

# Test Loss: 1.9270061254501343
# Test Accuracy: 0.6190476417541504

"""##Step 19 - Generate predictions"""

import numpy as np

y_true = []
y_pred = []

for images, labels in test_ds:

    predictions = model.predict(
        images,
        verbose=0
    )

    predictions = (predictions > 0.5).astype(int)

    y_true.extend(labels.numpy())
    y_pred.extend(predictions.flatten())

"""##Step 20 - Classification report"""

import numpy as np
from sklearn.metrics import classification_report

# Converting sigmoid output probabilities to binary 0 or 1 classes
y_pred_binary = (np.array(y_pred) > 0.5).astype(int)

print(
    classification_report(
        y_true,
        y_pred_binary,
        labels=[0, 1],
        target_names=class_names,
        zero_division=0
    )
)

"""##Step 21 - Confusion matrix"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# Convert sigmoid probabilities to binary 0 or 1 labels
y_pred_binary = (np.array(y_pred) > 0.5).astype(int)

# Generate confusion matrix
cm = confusion_matrix(y_true, y_pred_binary, labels=[0, 1])

# Plot heatmap
plt.figure(figsize=(6, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")
plt.show()

"""##Step 22 - test a single new image"""

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

image_path = "test_image.jpg"

# Load image using tf.keras.utils directly
image = tf.keras.utils.load_img(
    image_path,
    target_size=IMG_SIZE
)

image_array = tf.keras.utils.img_to_array(image)
image_array = tf.expand_dims(image_array, 0)  # Add batch dimension

# Make prediction
prediction = model.predict(image_array)
probability = prediction[0][0]

# Map predictions (0: Keyboard, 1: Mouse)
if probability >= 0.5:
    predicted_class = "Mouse"
    confidence = probability
else:
    predicted_class = "Keyboard"
    confidence = 1 - probability

# Display result
plt.imshow(image)
plt.axis("off")
plt.title(f"{predicted_class} ({confidence * 100:.2f}%)")
plt.show()

print("Prediction:", predicted_class)
print(f"Confidence: {confidence * 100:.2f}%")

plt.imshow(image)
plt.title(
    f"{predicted_class} - "
    f"{confidence * 100:.2f}%"
)
plt.axis("off")
plt.show()

"""##Step 23 - Save the trained model"""

model.save(
    "keyboard_mouse_cnn.keras"
)

# Write requirements to requirements.txt
requirements = """tensorflow
numpy
pandas
matplotlib
seaborn
scikit-learn
pillow
streamlit
"""

with open("requirements.txt", "w") as f:
    f.write(requirements.strip())

print("requirements.txt has been created successfully!")

"""##Step 24 - Save Locally"""

#Zip and Download Directly via Colab
import shutil
from google.colab import files

# Zip the CNN_Project folder
shutil.make_archive('CNN_Project', 'zip', 'CNN_Project')

# Download the zip file to your local computer
files.download('CNN_Project.zip')

